In [2]:
import numpy as np 
import pandas as pd

ModuleNotFoundError: No module named 'kagglehub'

In [ ]:
df = pd.read_csv('florida_housing.csv')
df

,type,sub_type,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,zip,sanitized_text
0,single_family,NaN,630000.0,605000,2274.0,1.0,2.0,3.0,2.0,2.0,2.0,2007.0,33446.0,"Beautiful 2 Bedroom + Den, 2.5 Bath Home - Mov..."
1,single_family,NaN,289000.0,285000,2170.0,1.0,3.0,2.0,2.0,2.0,2.0,1980.0,33876.0,Welcome to Florida living at its best! This 3-...
2,condos,condo,449000.0,425000,1722.0,NaN,3.0,2.0,2.0,2.0,2.0,2016.0,33913.0,Best Value in Casella and priced to sell... St...
3,single_family,NaN,599000.0,596000,1699.0,1.0,3.0,3.0,3.0,3.0,NaN,1952.0,33009.0,"Beautifully renovated 3-bedroom, 3-bathroom ho..."
4,single_family,NaN,173500.0,165000,640.0,1.0,1.0,1.0,1.0,1.0,NaN,1971.0,32118.0,Experience the ultimate beachfront lifestyle i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10888,condos,condo,169999.0,165000,1082.0,NaN,2.0,2.0,2.0,2.0,NaN,1965.0,33904.0,Direct Gulf Access Resort Lifestyle Just open ...
10889,condos,condo,579000.0,540000,1250.0,1.0,2.0,2.0,2.0,2.0,NaN,1999.0,33708.0,Enjoy the best of intercoastal living at Madei...
10890,townhomes,townhouse,309900.0,305000,1806.0,2.0,3.0,3.0,2.0,2.0,1.0,2006.0,32712.0,"This 3-bedroom, 2.5-bath end-unit townhome off..."
10891,townhomes,townhouse,639000.0,585000,1770.0,NaN,3.0,3.0,3.0,3.0,2.0,2011.0,33024.0,Welcome to Cooper City's highly sought-after g...
10892,townhomes,townhouse,960000.0,930000,2606.0,4.0,3.0,3.0,2.0,2.0,1.0,2017.0,33060.0,Rare 4-story marina-front townhome with ocean ...

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10893 entries, 0 to 10892
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             10893 non-null  object
 1   sub_type         2476 non-null   object
 2   listPrice        10881 non-null  float64
 3   lastSoldPrice    10893 non-null  int64
 4   sqft             10136 non-null  float64
 5   stories          9161 non-null   float64
 6   beds             10217 non-null  float64
 7   baths            10254 non-null  float64
 8   baths_full       10210 non-null  float64
 9   baths_full_calc  10210 non-null  float64
 10  garage           7306 non-null   float64
 11  year_built       10215 non-null  float64
 12  zip              10891 non-null  float64
 13  sanitized_text   10865 non-null  object
dtypes: float64(10), int64(1), object(3)
memory usage: 1.2+ MB

In [42]:
df.describe()

,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,zip
count,1.088100e+04,1.089300e+04,10136.000000,9161.000000,10217.000000,10254.000000,10210.000000,10210.000000,7306.000000,10215.000000,10891.000000
mean,5.863834e+05,5.579736e+05,1850.802289,1.308154,3.069981,2.443827,2.230362,2.230362,1.943471,1996.975624,33468.624093
std,1.272724e+06,1.144589e+06,922.388909,0.585215,1.021450,0.980903,0.793634,0.793634,0.686992,23.384010,822.937076
min,9.500000e+02,1.000000e+01,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1700.000000,32003.000000
25%,2.649000e+05,2.550000e+05,1306.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1980.000000,32778.000000
50%,3.750000e+05,3.650000e+05,1675.500000,1.000000,3.000000,2.000000,2.000000,2.000000,2.000000,1999.000000,33547.000000
75%,5.790000e+05,5.575000e+05,2182.000000,2.000000,4.000000,3.000000,2.000000,2.000000,2.000000,2020.000000,34119.000000
max,5.990000e+07,5.166718e+07,24829.000000,6.000000,20.000000,20.000000,20.000000,20.000000,16.000000,2027.000000,34997.000000

### Native accessors

Just like any other object, we can use the `.` to access the column in a DataFrame

In [31]:
df.listPrice

0        630000.0
1        289000.0
2        449000.0
3        599000.0
4        173500.0
           ...
10888    169999.0
10889    579000.0
10890    309900.0
10891    639000.0
10892    960000.0
Name: listPrice, Length: 10893, dtype: float64

In [32]:
df.beds

0        2.0
1        3.0
2        3.0
3        3.0
4        1.0
        ...
10888    2.0
10889    2.0
10890    3.0
10891    3.0
10892    3.0
Name: beds, Length: 10893, dtype: float64

Since the DataFrame is basically a dictionary of data, we can also access the columns using the indexing `[]` operator

In [33]:
# Same result using []
df['beds']

0        2.0
1        3.0
2        3.0
3        3.0
4        1.0
        ...
10888    2.0
10889    2.0
10890    3.0
10891    3.0
10892    3.0
Name: beds, Length: 10893, dtype: float64

To get a specific entry, we can use the `[]` operator once more

In [34]:
# Get the bedrooms of the first house
df['beds'][0]

np.float64(2.0)

Pandas provides us with using its built in indexing methods to access specific rows and columns, specifically the `loc` and `iloc`. <br> <br>
`loc` stands for **Location** and it understands the labels or names of the row/column. <br> <br>
`iloc` stands for **Integer Location** and it only understands the raw number positions, like standard Python lists.

#### The Problem
Imagine you have this simple DataFrame of 3 houses. Notice the row labels (the index) are custom string names. How do we get the price of House_C?

iloc only takes the row and column number as input.

Syntax:
`df.iloc[row_number, column_number]`

In [35]:
df.iloc[2,1]

'condo'

In [36]:
# Get the price of all houses
df.iloc[:,1]

0              NaN
1              NaN
2            condo
3              NaN
4              NaN
           ...
10888        condo
10889        condo
10890    townhouse
10891    townhouse
10892    townhouse
Name: sub_type, Length: 10893, dtype: object

In [37]:
df.iloc[:1, 1]

0    NaN
Name: sub_type, dtype: object

In [43]:
# get the first row in the dataframe
df.iloc[0]

type                                                   single_family
sub_type                                                         NaN
listPrice                                                   630000.0
lastSoldPrice                                                 605000
sqft                                                          2274.0
stories                                                          1.0
beds                                                             2.0
baths                                                            3.0
baths_full                                                       2.0
baths_full_calc                                                  2.0
garage                                                           2.0
year_built                                                    2007.0
zip                                                          33446.0
sanitized_text     Beautiful 2 Bedroom + Den, 2.5 Bath Home - Mov...
Name: 0, dtype: object

Both `loc` and `iloc` are row-first, column-second.

In [45]:
# Get the third and fourth entries
df.iloc[2:4]

,type,sub_type,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,zip,sanitized_text
2,condos,condo,449000.0,425000,1722.0,NaN,3.0,2.0,2.0,2.0,2.0,2016.0,33913.0,Best Value in Casella and priced to sell... St...
3,single_family,NaN,599000.0,596000,1699.0,1.0,3.0,3.0,3.0,3.0,NaN,1952.0,33009.0,"Beautifully renovated 3-bedroom, 3-bathroom ho..."

In [48]:
# Can also go backwards, getting the last 5 houses
df.iloc[-5:]

,type,sub_type,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,zip,sanitized_text
10888,condos,condo,169999.0,165000,1082.0,NaN,2.0,2.0,2.0,2.0,NaN,1965.0,33904.0,Direct Gulf Access Resort Lifestyle Just open ...
10889,condos,condo,579000.0,540000,1250.0,1.0,2.0,2.0,2.0,2.0,NaN,1999.0,33708.0,Enjoy the best of intercoastal living at Madei...
10890,townhomes,townhouse,309900.0,305000,1806.0,2.0,3.0,3.0,2.0,2.0,1.0,2006.0,32712.0,"This 3-bedroom, 2.5-bath end-unit townhome off..."
10891,townhomes,townhouse,639000.0,585000,1770.0,NaN,3.0,3.0,3.0,3.0,2.0,2011.0,33024.0,Welcome to Cooper City's highly sought-after g...
10892,townhomes,townhouse,960000.0,930000,2606.0,4.0,3.0,3.0,2.0,2.0,1.0,2017.0,33060.0,Rare 4-story marina-front townhome with ocean ...

In [51]:
# Get price of first listing
df.loc[0,'listPrice']

np.float64(630000.0)

We can modify the index row to our liking

In [54]:
df.set_index('zip')

,type,sub_type,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,sanitized_text
zip,,,,,,,,,,,,,
33446.0,single_family,NaN,630000.0,605000,2274.0,1.0,2.0,3.0,2.0,2.0,2.0,2007.0,"Beautiful 2 Bedroom + Den, 2.5 Bath Home - Mov..."
33876.0,single_family,NaN,289000.0,285000,2170.0,1.0,3.0,2.0,2.0,2.0,2.0,1980.0,Welcome to Florida living at its best! This 3-...
33913.0,condos,condo,449000.0,425000,1722.0,NaN,3.0,2.0,2.0,2.0,2.0,2016.0,Best Value in Casella and priced to sell... St...
33009.0,single_family,NaN,599000.0,596000,1699.0,1.0,3.0,3.0,3.0,3.0,NaN,1952.0,"Beautifully renovated 3-bedroom, 3-bathroom ho..."
32118.0,single_family,NaN,173500.0,165000,640.0,1.0,1.0,1.0,1.0,1.0,NaN,1971.0,Experience the ultimate beachfront lifestyle i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33904.0,condos,condo,169999.0,165000,1082.0,NaN,2.0,2.0,2.0,2.0,NaN,1965.0,Direct Gulf Access Resort Lifestyle Just open ...
33708.0,condos,condo,579000.0,540000,1250.0,1.0,2.0,2.0,2.0,2.0,NaN,1999.0,Enjoy the best of intercoastal living at Madei...
32712.0,townhomes,townhouse,309900.0,305000,1806.0,2.0,3.0,3.0,2.0,2.0,1.0,2006.0,"This 3-bedroom, 2.5-bath end-unit townhome off..."
33024.0,townhomes,townhouse,639000.0,585000,1770.0,NaN,3.0,3.0,3.0,3.0,2.0,2011.0,Welcome to Cooper City's highly sought-after g...
33060.0,townhomes,townhouse,960000.0,930000,2606.0,4.0,3.0,3.0,2.0,2.0,1.0,2017.0,Rare 4-story marina-front townhome with ocean ...

In [62]:
expensive = df[df['listPrice'] > 600000]
display(expensive)

,type,sub_type,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,zip,sanitized_text
0,single_family,NaN,630000.0,605000,2274.0,1.0,2.0,3.0,2.0,2.0,2.0,2007.0,33446.0,"Beautiful 2 Bedroom + Den, 2.5 Bath Home - Mov..."
7,single_family,NaN,695000.0,660000,3418.0,2.0,5.0,4.0,3.0,3.0,2.0,2012.0,32708.0,Short Sale. OWNER SAYS SELL!!! Mediterranean s...
12,single_family,NaN,799900.0,745000,1876.0,1.0,2.0,2.0,2.0,2.0,2.0,1999.0,34208.0,One-of-a-Kind Custom Waterfront Home | Oversiz...
13,single_family,NaN,2549000.0,2625000,3395.0,1.0,4.0,5.0,4.0,4.0,2.0,1991.0,32082.0,"Completely reimagined from the studs up, this ..."
14,single_family,NaN,644500.0,630000,2711.0,1.0,4.0,3.0,3.0,3.0,3.0,2005.0,34291.0,"47,[Redacted Entity]ION - Sellers Ready for Th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10869,condos,condo,945000.0,850000,1380.0,1.0,2.0,2.0,2.0,2.0,NaN,1983.0,33785.0,Welcome to the penthouse corner unit at Beach ...
10875,single_family,NaN,623586.0,620000,2582.0,2.0,4.0,4.0,3.0,3.0,2.0,2026.0,34241.0,Under Construction. What's Special: Close to A...
10879,single_family,NaN,675000.0,640000,2297.0,1.0,4.0,2.0,2.0,2.0,2.0,2025.0,32833.0,One or more photo(s) has been virtually staged...
10891,townhomes,townhouse,639000.0,585000,1770.0,NaN,3.0,3.0,3.0,3.0,2.0,2011.0,33024.0,Welcome to Cooper City's highly sought-after g...
10892,townhomes,townhouse,960000.0,930000,2606.0,4.0,3.0,3.0,2.0,2.0,1.0,2017.0,33060.0,Rare 4-story marina-front townhome with ocean ...

In [64]:
df.loc[(df.listPrice > 600000) & (df.beds > 3)]

,type,sub_type,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,zip,sanitized_text
7,single_family,NaN,695000.0,660000,3418.0,2.0,5.0,4.0,3.0,3.0,2.0,2012.0,32708.0,Short Sale. OWNER SAYS SELL!!! Mediterranean s...
13,single_family,NaN,2549000.0,2625000,3395.0,1.0,4.0,5.0,4.0,4.0,2.0,1991.0,32082.0,"Completely reimagined from the studs up, this ..."
14,single_family,NaN,644500.0,630000,2711.0,1.0,4.0,3.0,3.0,3.0,3.0,2005.0,34291.0,"47,[Redacted Entity]ION - Sellers Ready for Th..."
15,single_family,NaN,5595000.0,5250000,7059.0,2.0,6.0,9.0,7.0,7.0,3.0,2025.0,32461.0,"Welcome to 92 Quail Hollow Court, an extraordi..."
17,single_family,NaN,1395000.0,1350000,3411.0,2.0,4.0,3.0,3.0,3.0,3.0,2014.0,32081.0,SIMPLY OUTSTANDING | Luxury Lakeview Pool Home...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10864,single_family,NaN,615000.0,610000,1800.0,1.0,4.0,3.0,3.0,3.0,NaN,1950.0,33607.0,Beautiful Fully Renovated Home. This property ...
10865,single_family,NaN,1200000.0,1200000,3663.0,2.0,6.0,6.0,5.0,5.0,2.0,2016.0,34747.0,"Six-bedroom modern custom home, featuring a pr..."
10866,single_family,NaN,668990.0,668990,2560.0,2.0,4.0,4.0,3.0,3.0,2.0,2025.0,34715.0,"Beautiful 4 bedroom, 3 and a half bath home"
10875,single_family,NaN,623586.0,620000,2582.0,2.0,4.0,4.0,3.0,3.0,2.0,2026.0,34241.0,Under Construction. What's Special: Close to A...
10879,single_family,NaN,675000.0,640000,2297.0,1.0,4.0,2.0,2.0,2.0,2.0,2025.0,32833.0,One or more photo(s) has been virtually staged...

the `isin()` lets you select data whose value "is in" a list of values.

In [69]:
small = df[df.type.isin(["single_family", "condos"])]


#alternate 
small = df.loc[df.type.isin(["single_family", "condos"])]
display(small)

,type,sub_type,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,zip,sanitized_text
0,single_family,NaN,630000.0,605000,2274.0,1.0,2.0,3.0,2.0,2.0,2.0,2007.0,33446.0,"Beautiful 2 Bedroom + Den, 2.5 Bath Home - Mov..."
1,single_family,NaN,289000.0,285000,2170.0,1.0,3.0,2.0,2.0,2.0,2.0,1980.0,33876.0,Welcome to Florida living at its best! This 3-...
2,condos,condo,449000.0,425000,1722.0,NaN,3.0,2.0,2.0,2.0,2.0,2016.0,33913.0,Best Value in Casella and priced to sell... St...
3,single_family,NaN,599000.0,596000,1699.0,1.0,3.0,3.0,3.0,3.0,NaN,1952.0,33009.0,"Beautifully renovated 3-bedroom, 3-bathroom ho..."
4,single_family,NaN,173500.0,165000,640.0,1.0,1.0,1.0,1.0,1.0,NaN,1971.0,32118.0,Experience the ultimate beachfront lifestyle i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10885,single_family,NaN,150000.0,141000,1032.0,1.0,3.0,2.0,1.0,1.0,NaN,1960.0,32935.0,"Investor special in Melbourne, FL near Post & ..."
10886,single_family,NaN,312500.0,310000,1208.0,1.0,3.0,2.0,2.0,2.0,2.0,2004.0,32703.0,Buyer's financing fell through - their loss is...
10887,single_family,NaN,599900.0,575000,2269.0,1.0,3.0,2.0,2.0,2.0,2.0,2020.0,32179.0,"PRICE IMPROVEMENT - NOW $599,900. One of the f..."
10888,condos,condo,169999.0,165000,1082.0,NaN,2.0,2.0,2.0,2.0,NaN,1965.0,33904.0,Direct Gulf Access Resort Lifestyle Just open ...
10889,condos,condo,579000.0,540000,1250.0,1.0,2.0,2.0,2.0,2.0,NaN,1999.0,33708.0,Enjoy the best of intercoastal living at Madei...

In [74]:
# Get all rows with non-null sub-type
df.loc[df.sub_type.notnull()]

,type,sub_type,listPrice,lastSoldPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage,year_built,zip,sanitized_text
2,condos,condo,449000.0,425000,1722.0,NaN,3.0,2.0,2.0,2.0,2.0,2016.0,33913.0,Best Value in Casella and priced to sell... St...
5,townhomes,townhouse,329000.0,305000,1760.0,2.0,3.0,3.0,2.0,2.0,1.0,2007.0,33928.0,Welcome to this beautifully remodeled Copper O...
25,condos,condo,949000.0,910000,1385.0,NaN,2.0,2.0,2.0,2.0,NaN,1984.0,32550.0,Experience elevated Gulf-front living in this ...
27,condos,condo,399000.0,399000,2284.0,2.0,3.0,2.0,2.0,2.0,2.0,2019.0,34293.0,Live in this beautiful TOP FLOOR END UNIT cond...
30,condos,condo,199000.0,190000,916.0,4.0,2.0,2.0,2.0,2.0,NaN,1982.0,33434.0,CENTURY VILLAGE--ACTIVE ADULT COMMUNITY. LOCAT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10888,condos,condo,169999.0,165000,1082.0,NaN,2.0,2.0,2.0,2.0,NaN,1965.0,33904.0,Direct Gulf Access Resort Lifestyle Just open ...
10889,condos,condo,579000.0,540000,1250.0,1.0,2.0,2.0,2.0,2.0,NaN,1999.0,33708.0,Enjoy the best of intercoastal living at Madei...
10890,townhomes,townhouse,309900.0,305000,1806.0,2.0,3.0,3.0,2.0,2.0,1.0,2006.0,32712.0,"This 3-bedroom, 2.5-bath end-unit townhome off..."
10891,townhomes,townhouse,639000.0,585000,1770.0,NaN,3.0,3.0,3.0,3.0,2.0,2011.0,33024.0,Welcome to Cooper City's highly sought-after g...
10892,townhomes,townhouse,960000.0,930000,2606.0,4.0,3.0,3.0,2.0,2.0,1.0,2017.0,33060.0,Rare 4-story marina-front townhome with ocean ...

### The "Gotcha"
If you don't assign custom names to your rows (which most people don't), your row labels default to 0, 1, 2, 3...

Because of this, .loc[0] and .iloc[0] look like they are doing the same thing. But they aren't!

.iloc[0] means "Give me the first row in the file".
.loc[0] means "Give me the row whose custom name plate happens to be '0'".
If you sort or shuffle your data, the row named '0' might now be at the bottom of the table. In that case, .iloc[0] grabs the new top row, but .loc[0] shoots down to the bottom to find the row with the name plate '0'.

If we do .loc(0:100), it will actually return 101 rows, both indexes are inclusive, since the loc function returns the rows named '0' all the way to the row named '100'

count    1.088100e+04
mean     5.863834e+05
std      1.272724e+06
min      9.500000e+02
25%      2.649000e+05
50%      3.750000e+05
75%      5.790000e+05
max      5.990000e+07
Name: listPrice, dtype: float64

In [78]:
display(df.type.unique())

display(df.sub_type.unique())

array(['single_family', 'condos', 'townhomes', 'multi_family', 'land',
       'mobile', 'condo_townhome_rowhome_coop', 'farm'], dtype=object)

array([nan, 'condo', 'townhouse'], dtype=object)

In [79]:
df.type.value_counts()

type
single_family                  7101
condos                         1702
townhomes                       762
land                            641
mobile                          560
multi_family                    111
condo_townhome_rowhome_coop      13
farm                              3
Name: count, dtype: int64