# 🐼 Pandas Interactive Crash Course

In Machine Learning, 80% of your time is spent cleaning and preparing data. **Pandas** is the industry standard tool for this.

This notebook will guide you through the essentials. **Select each code block and press `Shift + Enter` to run it.**

### Step 1: Import the Library
We always import pandas as `pd`. We're also importing `numpy` as `np` because pandas uses it under the hood.

In [28]:
import pandas as pd
import numpy as np

print('Pandas successfully imported!')

Pandas successfully imported!

### Step 2: Let's create some dummy mock data!
Usually, you read CSV files directly. For this tutorial, let's create a messy dataset simulating user data for an app.

In [43]:
# Creating a dictionary of lists
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Age': [25, np.nan, 35, 42, 28, 55, 31, np.nan], # np.nan means missing data!
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'New York', 'Chicago', 'Miami', 'Seattle'],
    'Salary': [70000, 85000, 120000, 95000, 72000, 150000, 90000, 110000],
    'Premium_Member': [True, False, True, False, False, True, True, False]
}

# Convert it into a Pandas DataFrame
df = pd.DataFrame(data)
df

      Name   Age         City  Salary  Premium_Member
0    Alice  25.0     New York   70000            True
1      Bob   NaN  Los Angeles   85000           False
2  Charlie  35.0      Chicago  120000            True
3    David  42.0      Houston   95000           False
4      Eve  28.0     New York   72000           False
5    Frank  55.0      Chicago  150000            True
6    Grace  31.0        Miami   90000            True
7    Heidi   NaN      Seattle  110000           False

### Step 3: Inspecting your Data
When you load millions of rows, you can't just print `df`. You need tools to inspect it efficiently.

In [30]:
# .head(n) shows the first n rows. Try changing it to df.head(3)
display(df.head())

# .info() tells you about missing values and data types
print('\n--- Data Info ---')
df.info()

# .describe() gives you instant math statistics on numerical columns
print('\n--- Statistics ---')
display(df.describe())

      Name   Age         City  Salary  Premium_Member
0    Alice  25.0     New York   70000            True
1      Bob   NaN  Los Angeles   85000           False
2  Charlie  35.0      Chicago  120000            True
3    David  42.0      Houston   95000           False
4      Eve  28.0     New York   72000           False

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            8 non-null      object
 1   Age             6 non-null      float64
 2   City            8 non-null      object
 3   Salary          8 non-null      int64
 4   Premium_Member  8 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(2)
memory usage: 392.0+ bytes

--- Statistics ---

             Age         Salary
count   6.000000       8.000000
mean   36.000000   99000.000000
std    11.027239   26795.522014
min    25.000000   70000.000000
25%    28.750000   81750.000000
50%    33.000000   92500.000000
75%    40.250000  112500.000000
max    55.000000  150000.000000

### Step 4: Selecting Data
How do we grab specific columns or rows?

In [33]:
# Select a single column (Notice it returns a 'Series' - perfectly formatted 1D array)
display(df['City'])

# Select multiple columns (Pass a list of column names inside the brackets!)
display(df[['Name', 'Salary']])

display(df[["Name", "City", "Premium_Member"]])

0       New York
1    Los Angeles
2        Chicago
3        Houston
4       New York
5        Chicago
6          Miami
7        Seattle
Name: City, dtype: object

      Name  Salary
0    Alice   70000
1      Bob   85000
2  Charlie  120000
3    David   95000
4      Eve   72000
5    Frank  150000
6    Grace   90000
7    Heidi  110000

      Name         City  Premium_Member
0    Alice     New York            True
1      Bob  Los Angeles           False
2  Charlie      Chicago            True
3    David      Houston           False
4      Eve     New York           False
5    Frank      Chicago            True
6    Grace        Miami            True
7    Heidi      Seattle           False

### Step 5: Filtering Data 
Filtering in Pandas is incredibly powerful. We use boolean conditions inside brackets.

In [37]:
# Let's find everyone making over 90,000
high_earners = df[df['Salary'] > 90000]
display('High Earners:', high_earners)

# Who lives in Chicago?
chicagos = df[df['City'] == 'Chicago']
display('Chicago dudes:', chicagos)

# Multiple conditions: Over 30 AND Premium Member
# Note: & is AND, | is OR. You MUST use parentheses around conditions.
target_users = df[(df['Age'] > 30) & (df['Premium_Member'] == True)]
display('Target Users:', target_users)

'High Earners:'

      Name   Age     City  Salary  Premium_Member
2  Charlie  35.0  Chicago  120000            True
3    David  42.0  Houston   95000           False
5    Frank  55.0  Chicago  150000            True
7    Heidi   NaN  Seattle  110000           False

'Chicago dudes:'

      Name   Age     City  Salary  Premium_Member
2  Charlie  35.0  Chicago  120000            True
5    Frank  55.0  Chicago  150000            True

'Target Users:'

      Name   Age     City  Salary  Premium_Member
2  Charlie  35.0  Chicago  120000            True
5    Frank  55.0  Chicago  150000            True
6    Grace  31.0    Miami   90000            True

### Step 6: Handling Missing Data
Real data is messy. Notice how Bob and Heidi don't have their age listed (`NaN`). ML algorithms will crash if you feed them `NaN`.

In [44]:
# Strategy 1: Drop any rows with missing data
df_dropped = df.dropna()
display('After Dropping Rows:', df_dropped)

# Strategy 2 (Better): Fill missing data with the average (mean) age
average_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(average_age)

display('Missing Data Filled:', df)

'After Dropping Rows:'

      Name   Age      City  Salary  Premium_Member
0    Alice  25.0  New York   70000            True
2  Charlie  35.0   Chicago  120000            True
3    David  42.0   Houston   95000           False
4      Eve  28.0  New York   72000           False
5    Frank  55.0   Chicago  150000            True
6    Grace  31.0     Miami   90000            True

'Missing Data Filled:'

      Name   Age         City  Salary  Premium_Member
0    Alice  25.0     New York   70000            True
1      Bob  36.0  Los Angeles   85000           False
2  Charlie  35.0      Chicago  120000            True
3    David  42.0      Houston   95000           False
4      Eve  28.0     New York   72000           False
5    Frank  55.0      Chicago  150000            True
6    Grace  31.0        Miami   90000            True
7    Heidi  36.0      Seattle  110000           False

### Step 7: Feature Engineering (Creating new columns)
In ML, you often create new features to help the model learn better.

In [45]:
# Let's calculate estimated tax (assuming 20% rate)
# Pandas does this for the ENTIRE column instantly, no for-loops needed!
df['Estimated_Tax'] = df['Salary'] * 0.20

# Let's convert City names to lowercase so our ML model maps them correctly
df['City'] = df['City'].str.lower()

df

      Name   Age         City  Salary  Premium_Member  Estimated_Tax
0    Alice  25.0     new york   70000            True        14000.0
1      Bob  36.0  los angeles   85000           False        17000.0
2  Charlie  35.0      chicago  120000            True        24000.0
3    David  42.0      houston   95000           False        19000.0
4      Eve  28.0     new york   72000           False        14400.0
5    Frank  55.0      chicago  150000            True        30000.0
6    Grace  31.0        miami   90000            True        18000.0
7    Heidi  36.0      seattle  110000           False        22000.0

### Step 8: Grouping Data (Like SQL GroupBy)
Grouping allows you to calculate statistics across categories.

In [46]:
# What is the average salary per city?
avg_salary_by_city = df.groupby('City')['Salary'].mean()
display('Average Salary by City:', avg_salary_by_city)

# Are premium members older on average?
age_by_membership = df.groupby('Premium_Member')['Age'].mean()
display('Average Age by Membership:', age_by_membership)

'Average Salary by City:'

City
chicago        135000.0
houston         95000.0
los angeles     85000.0
miami           90000.0
new york        71000.0
seattle        110000.0
Name: Salary, dtype: float64

'Average Age by Membership:'

Premium_Member
False    35.5
True     36.5
Name: Age, dtype: float64

### Summary
You just learned how to:
1. Create DataFrames
2. Inspect Data (`.head()`, `.info()`, `.describe()`)
3. Select & Filter Rows
4. Clean Data (`.fillna()`)
5. Create New Features
6. Group Data

**These 6 things make up 90% of what you'll use Pandas for in Machine Learning!**

## Complex Query
I need a table showing only the 'Electronics' and 'Home' categories. I want to see the total number of items sold, the average price of those items, and the number of returned items per category. Oh, and only include purchases over $50. Finally, please sort the results so the category with the highest average price is at the top.

In [47]:
np.random.seed(42) # So we get the same random numbers
sales_data = {
    'Customer_ID': np.random.randint(1000, 1020, 100),
    'Category': np.random.choice(['Electronics', 'Clothing', 'Home', 'Toys'], 100),
    'Price': np.random.uniform(10, 500, 100).round(2),
    'Is_Returned': np.random.choice([True, False], 100, p=[0.15, 0.85]) # 15% return rate
}
sales_df = pd.DataFrame(sales_data)

sales_df

    Customer_ID  Category   Price  Is_Returned
0          1006      Home  264.21        False
1          1019      Toys  354.48         True
2          1014      Toys  188.18        False
3          1010  Clothing  486.17        False
4          1007      Home  481.60        False
..          ...       ...     ...          ...
95         1011      Toys  256.29        False
96         1001      Home  292.68         True
97         1000      Home  251.33         True
98         1015  Clothing  105.67         True
99         1004      Toys  364.00         True

[100 rows x 4 columns]

In [62]:
report = (
    # Notice we combine them inside ONE pair of brackets using '&'
    sales_df[sales_df["Price"] > 50] [sales_df["Category"].isin(["Electronics", "Home"])]
    .groupby("Category")
    .agg(
        Total_Items_Sold=('Customer_ID', 'count'), # Count total rows per category
        Average_Price=('Price', 'mean'),           # Find average price
        Items_Returned=('Is_Returned', 'sum')      # Summing booleans counts the True values!
    )
    .sort_values(by="Average_Price", ascending=False)
    .round(2)
    )

display(report)

/tmp/ipykernel_110713/3377573822.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sales_df[sales_df["Price"] > 50] [sales_df["Category"].isin(["Electronics", "Home"])]

             Total_Items_Sold  Average_Price  Items_Returned
Category
Home                       29         250.86               4
Electronics                24         250.09               5

         Bedrooms   Price
House_A         3  500000
House_B         4  800000
House_C         1  150000

np.int64(800000)